Uart state machine and proofs
project-oak/silveroak pull request #853
Opened 2021-07-24 00:33 UTC by dayeol

This branch is based off of `generalize-libs` branch, so that needs to be merged before this branch could be merged.
This PR adds the state machine model for Uart device, and define & prove the specifications of the driver functions.

2021-07-26 14:18 UTC, samuelgruetter commented on investigations/bedrock2/Uart/UartSemantics.v
> +      else
what if `t > 32`?

2021-07-26 14:22 UTC, samuelgruetter commented on investigations/bedrock2/Uart/UartSemantics.v
> +         sz = 4%nat /\ write_step s a v s' ;
can Uart write single bytes? If so, you'll have to move the `sz` argument into `write_step`

2021-07-26 14:28 UTC, samuelgruetter commented
(also, since I couldn't find any PR for the `generalize-libs`, I reviewed both the generalize libs part and the uart part in this PR)

2021-07-26 17:43 UTC, dayeol commented on investigations/bedrock2/LibBase/AbsMMIOProperties.v
> +          exists val, val = value
fixed.

2021-07-26 17:43 UTC, dayeol commented on investigations/bedrock2/LibBase/AbsMMIOProperties.v
> +          exists val, val = value
fixed

2021-07-26 17:51 UTC, dayeol commented on investigations/bedrock2/LibBase/AbsMMIOProperties.v
> +Require Import Cava.Util.Tactics.
good point

2021-07-26 17:51 UTC, dayeol commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +Require Import Cava.Util.Tactics.
fixed

2021-07-26 17:51 UTC, dayeol commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +      forall (field mask index : Semantics.word) (R : mem -> Prop) (m : mem) (t : trace),
fixed

2021-07-26 17:51 UTC, dayeol commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +      forall (field index: Semantics.word) (R : mem -> Prop) (m : mem) (t : trace),
fixed

2021-07-26 17:56 UTC, dayeol commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +          v = select_bits field index mask
fixed

2021-07-26 17:56 UTC, dayeol commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +    eexists; ssplit; repeat straightline_with_map_lookup.
we do need straightline_with_map_lookup.

2021-07-27 06:02 UTC, dayeol commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +    eexists; ssplit; repeat straightline_with_map_lookup.
it seems that we still need `straightline_with_map_lookup`

2021-07-27 06:23 UTC, dayeol commented on investigations/bedrock2/Aes/AesProperties.v
> -    read_status.
fixed by adding a general lemma `read_flag_from_status`.
It required an unnecessary hypothesis `i <= i` because bedrock2 issue (#854)

2021-07-27 06:25 UTC, dayeol commented
In order to keep this PR separate from #849, I have applied all the changes for `Aes` or `LibBase` to that one.

2021-07-27 13:36 UTC, samuelgruetter commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +    eexists; ssplit; repeat straightline_with_map_lookup.
hmm this is something I should look at then... could you replace it by something a bit more verbose that exposes where it's needed, eg `eexists; ssplit; repeat straightline. straightline_with_map_lookup. repeat straightline.` or similar and put a TODO there?

2021-07-27 23:57 UTC, dayeol commented on investigations/bedrock2/Uart/UartProperties.v
> +Require Import Cava.Util.Tactics.
We needed Cava for boolsimpl tactic defined in Cava.Util.Tactics.

2021-07-28 00:01 UTC, dayeol commented on investigations/bedrock2/Uart/UartSemantics.v
> +  Definition status_matches_state (s : state) (status : word) : bool :=
Yes, I think it was for consistency with `AesSemantics`

2021-07-28 00:02 UTC, dayeol commented on investigations/bedrock2/Uart/UartSemantics.v
> +         sz = 4%nat /\ write_step s a v s' ;
it doesn't

2021-07-28 09:40 UTC, jadephilipoom commented on investigations/bedrock2/Uart/UartProperties.v
> +Require Import Cava.Util.Tactics.
Depending on Cava.Util should be okay, none of the things there are at all cava-specific.

2021-07-28 10:07 UTC, jadephilipoom requested changes
A few small-scale things still need to be addressed, but the overall structure and design here looks great!

2021-07-28 10:07 UTC, jadephilipoom commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +      forall (field mask index : Semantics.word) (R : mem -> Prop) (m : mem) (t : trace),
Again, apologies if I'm missing something that the two of you agreed on, but it looks like `R` is still present and still unused; I had the same comment as Sam before looking at the resolved conversation.

2021-07-28 10:07 UTC, jadephilipoom commented on investigations/bedrock2/WordProperties.v
> +      rewrite word.unsigned_of_Z in E1.
Might be able to replace at least some of these with `autorewrite with push_unsigned in E1`?

2021-07-28 17:37 UTC, dayeol commented on investigations/bedrock2/Aes/AesProperties.v
> +
fixed

2021-07-28 17:48 UTC, dayeol commented on investigations/bedrock2/Aes/AesProperties.v
> +      destruct H4. destruct H2.
fixed

2021-07-28 17:51 UTC, dayeol commented on investigations/bedrock2/LibBase/AbsMMIOProperties.v
> +          /\ (exists s'', execution tr' s'')
I think s' and s'' can be equivalent only if the execution is unique, s.t.,
`execution tr s -> execution tr s' -> s = s'`
where as in this spec it is not.

2021-07-28 17:53 UTC, dayeol commented on investigations/bedrock2/LibBase/AbsMMIOProperties.v
> +        (exists val s', parameters.read_step 1 s r val s') ->
fixed

2021-07-28 17:57 UTC, dayeol commented on investigations/bedrock2/WordProperties.v
> +      rewrite word.unsigned_of_Z in E1.
fixed

2021-07-28 18:01 UTC, dayeol commented on investigations/bedrock2/LibBase/BitfieldProperties.v
> +    eexists; ssplit; repeat straightline_with_map_lookup.
fixed

2021-07-28 18:27 UTC, dayeol commented
Addressed all the comments

2021-07-28 18:43 UTC, samuelgruetter approved these changes

2021-07-29 09:15 UTC, jadephilipoom approved these changes

2021-07-29 16:53 UTC, merged