Uart semantics and proofs (cont'd)
project-oak/silveroak pull request #888
Opened 2021-08-12 06:51 UTC by dayeol

This completes the spec & proof of the following function
- `uart_putchar`

The function has 2 while loops: at the beginning to make sure the tx FIFO is not full, and at the end to ensure the device is back to IDLE state.
For now, it has been proven with the precondition where the device state is always IDLE when we enter the function.
This makes the first loop iterate exactly once.
It makes sense in a single-threaded environment because the only way to make the device busy is via `uart_putchar`, 
but the function waits the device to be IDLE state before it returns.
However, we could also generalize it by relaxing the precondition to be `execution tr s` for any state `s`,
and it would be pretty straightforward to prove that too -- `s` can be destructed, and if `s` is `IDLE` we just do the same thing, and if `s` is `BUSY` then we can prove that at some point the loop should break leaving the device in `IDLE` state.

2021-08-12 09:25 UTC, jadephilipoom requested changes
The UART proofs look good, great work! However, I want to resolve the point about `IncrementWait` before merging.

2021-08-12 09:25 UTC, jadephilipoom commented on firmware/Uart/UartSemantics.v
> +    Nat.ltb (ncycles_processing) (fifo_depth * ncycles_processing) = true.
These `Axiom`s will be impossible to instantiate later; if I were to prove that my `ncycles_processing` is nonzero, I can't then use that proof to make the UART programs' correctness proofs no longer depend on the axiom. If you instead introduce these with `Context`, though, the proofs will just show up with preconditions that can be elimated later.

2021-08-12 16:22 UTC, samuelgruetter requested changes

2021-08-12 16:22 UTC, samuelgruetter commented on firmware/Uart/UartProperties.v
> +      execution tr IDLE ->
Do you think it would be too hard to allow any `s` here?

2021-08-12 16:22 UTC, samuelgruetter commented on firmware/IncrementWait/IncrementWait.v
> +        abs_mmio_write32 (VALUE_ADDR, input) ;
I agree that it would be good to keep `IncrementWait` small, and also without admitted lemmas like `status_read_always_ok` in `IncrementWaitProperties.v`. Is there much insight in the changes you did to `IncrementWait` that have not yet made it into `Uart`? If yes, we should probably copy the directory, but if no, it would be better to avoid the duplication, because every future change/refactoring will have to be applied to two instead of one directory. Alternatively, we could also keep it around on a separate branch, maybe?

2021-08-13 03:56 UTC, dayeol commented on firmware/IncrementWait/IncrementWait.v
> +        abs_mmio_write32 (VALUE_ADDR, input) ;
Good point, I think I can just omit `IncrementWait` from this PR as it was mostly practice.
Also I was kinda rushing when I submit this PR (cuz it's my second from the last day), so I did not spend much time to make `IncrementWait` look good. It'll be better to have a separate branch or directory and polish a bit if we are gonna include it.

2021-08-13 21:00 UTC, dayeol commented on firmware/Uart/UartSemantics.v
> +            then s' = BUSY (tx + (ncycles_processing))
I think it needs to be `(fifo_depth - 1) * ncycles_processing` so that the maximum number of busy cycles is `fifo_depth * ncycles_processing`. I fixed it and also I'll try to write the invariant.

2021-08-13 21:32 UTC, dayeol commented on firmware/Uart/UartSemantics.v
> +    Nat.ltb (ncycles_processing) (fifo_depth * ncycles_processing) = true.
Thanks for the comments! But it turns out that we didn't even need the axioms, so I eradicated those.

2021-08-16 07:30 UTC, dayeol commented on firmware/Uart/UartSemantics.v
> +            \/ (exists n', n = S n' /\ status_matches_state s' val = true /\ s' = BUSY n')
fixed

2021-08-16 07:52 UTC, dayeol commented on firmware/Uart/UartProperties.v
> +      execution tr IDLE ->
This is possible but I think it could be another huge change so can we make this a new PR?

2021-08-16 07:54 UTC, dayeol commented on firmware/Uart/UartSemantics.v
> +            then s' = BUSY (tx + (ncycles_processing))
Can we make this a new PR too? seems like it will need some time for me

2021-08-16 07:57 UTC, dayeol commented
@googlebot I signed it!

2021-08-16 13:16 UTC, samuelgruetter approved these changes

2021-08-16 13:16 UTC, samuelgruetter commented on firmware/Uart/Uart.v
> +        (* s = IDLE *)
these comments don't immediately make sense to me, are they just some sample run?

2021-08-16 13:16 UTC, samuelgruetter commented on firmware/Uart/UartSemantics.v
> +    status_matches_state s' val = true /\
I think the line `status_matches_state s' val = true` should be 2 lines further down, because it only needs to hold if we want to read the `STATUS` register. (But it doesn't matter (yet) because currently the `STATUS` register is the only readable register).

2021-08-16 18:24 UTC, dayeol commented on firmware/Uart/Uart.v
> +        (* s = IDLE *)
removed!

2021-08-16 19:03 UTC, samuelgruetter commented on firmware/Uart/Uart.v
> +        (* s = IDLE *)
did you also push it? (I can't see it here)

2021-08-16 19:05 UTC, dayeol commented on firmware/Uart/Uart.v
> +        (* s = IDLE *)
no, not yet, I usually resolve the comments when I fix & test on my local. I'll push it soon.

2021-08-16 19:06 UTC, dayeol commented on firmware/Uart/UartSemantics.v
> +    status_matches_state s' val = true /\
fixed.

2021-08-16 19:10 UTC, dayeol commented on firmware/Uart/UartProperties.v
> +      execution tr IDLE ->
#897

2021-08-16 19:14 UTC, dayeol commented on firmware/Uart/UartSemantics.v
> +            then s' = BUSY (tx + (ncycles_processing))
#898

2021-08-16 19:16 UTC, samuelgruetter approved these changes

2021-08-16 19:20 UTC, samuelgruetter commented
It seems that @jadephilipoom's as well as my requested changes have been addressed, or turned into new issues, so I'm going to merge this now, so that I can make my next PR on top of it.

2021-08-16 19:21 UTC, merged

2021-08-16 19:23 UTC, samuelgruetter commented
Thanks @dayeol for dealing with all my nitpicks 😉